// Generated by ReScript, PLEASE EDIT WITH CARE


function DeepNested$A$B$C(props) {
  return "String";
}

let C = {
  make: DeepNested$A$B$C
};

let B = {
  C: C
};

let A = {
  B: B
};

export {
  A,
}
/* No side effect */
