// Generated by ReScript, PLEASE EDIT WITH CARE


function sum(a, b) {
  return a + b | 0;
}

function DeepNested$A$B$C(props) {
  return "String";
}

let C = {
  make: DeepNested$A$B$C
};

function DeepNested$A$B$D(props) {
  return 3;
}

let D = {
  make: DeepNested$A$B$D
};

let B = {
  sum: sum,
  C: C,
  D: D
};

let A = {
  B: B
};

export {
  A,
}
/* No side effect */
