// Generated by ReScript, PLEASE EDIT WITH CARE


function sum(a, b) {
  return a + b | 0;
}

function Initial(props) {
  'react/jsx-runtime';
  return "String";
}

let make = Initial;

export {
  sum,
  make,
}
/* No side effect */
