// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodepath from "node:path";
import * as Promises from "node:fs/promises";

let Chunk = {};

let ChildProcess = {
  Chunk: Chunk
};

let Process = {};

let Url = {};

let ImportMeta = {};

function changeExtension(path, ext) {
  let result = Nodepath.parse(path);
  result.ext = ext;
  result.base = result.name + ext;
  return Nodepath.format(result);
}

let Path = {
  changeExtension: changeExtension
};

let Constants = {};

async function fileExists(path) {
  try {
    await access(path, Promises.constants.R_OK);
    return true;
  } catch (exn) {
    return false;
  }
}

let FsPromises = {
  Constants: Constants,
  fileExists: fileExists
};

export {
  ChildProcess,
  Process,
  Url,
  ImportMeta,
  Path,
  FsPromises,
}
/* node:path Not a pure module */
