// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DaxSh from "dax-sh";
import * as Semver from "semver";
import * as Picocolors from "picocolors";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

async function rescript(param) {
  let rescriptVersionText = await DaxSh.$`rescript --version`.text();
  let rescriptVersion = rescriptVersionText.split(" ").at(-1);
  if (!Semver.satisfies(rescriptVersion, ">=12.0.0-beta.1")) {
    throw {
      RE_EXN_ID: "Failure",
      _1: "Rescript version must be >=12.0.0-beta.1",
      Error: new Error()
    };
  }
  let platformImport = await import(`@rescript/` + process.platform + `-` + process.arch);
  let rescriptBin;
  if (typeof platformImport === "object" && platformImport !== null && !Array.isArray(platformImport)) {
    let match = platformImport.binPaths;
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      let rescriptBin$1 = match.rescript_exe;
      if (typeof rescriptBin$1 === "string") {
        rescriptBin = rescriptBin$1;
      } else {
        throw {
          RE_EXN_ID: "Failure",
          _1: "Failed to resolve rescript.exe",
          Error: new Error()
        };
      }
    } else {
      throw {
        RE_EXN_ID: "Failure",
        _1: "Failed to resolve rescript.exe",
        Error: new Error()
      };
    }
  } else {
    throw {
      RE_EXN_ID: "Failure",
      _1: "Failed to resolve rescript.exe",
      Error: new Error()
    };
  }
  let pluginState = {
    rescriptBin: rescriptBin,
    logger: {
      info: (msg, optionsOpt) => {
        console.log(msg);
      },
      warn: (msg, optionsOpt) => {
        console.warn(msg);
      },
      error: (msg, optionsOpt) => {
        console.log(msg);
      }
    },
    command: "build",
    runningRewatch: undefined
  };
  return {
    name: "rescript",
    enforce: "pre",
    config: () => ({
      server: {
        watch: {
          ignored: [
            "**/lib/**",
            "**/*.res",
            "**/*.resi"
          ]
        }
      }
    }),
    configResolved: async resolvedConfig => {
      pluginState.logger = resolvedConfig.logger;
      pluginState.command = resolvedConfig.command;
    },
    buildStart: async () => {
      pluginState.logger.info(Picocolors.whiteBright(`About to build ReScript project with version ` + rescriptVersion), {
        timestamp: true
      });
      let match = pluginState.command;
      if (match === "serve") {
        pluginState.runningRewatch = DaxSh.$`${pluginState.rescriptBin} watch`.noThrow().spawn();
        return;
      }
      await DaxSh.$`rescript build`;
    },
    closeBundle: async () => {
      let cp = pluginState.runningRewatch;
      if (cp === undefined) {
        return;
      }
      pluginState.logger.info(Picocolors.whiteBright("About to kill ReScript process"), {
        timestamp: true
      });
      pluginState.runningRewatch = undefined;
      cp.kill("SIGKILL");
      try {
        await cp;
        return;
      } catch (raw_e) {
        let e = Primitive_exceptions.internalToException(raw_e);
        if (e.RE_EXN_ID === "JsExn") {
          return pluginState.logger.error(Picocolors.red(`Failed to kill rescript watch`), undefined);
        }
        throw e;
      }
    }
  };
}

let $$default = rescript;

export {
  rescript,
  $$default as default,
}
/* dax-sh Not a pure module */
