// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NpmRunPath from "npm-run-path";
import * as Promises from "node:fs/promises";
import * as Nodechild_process from "node:child_process";

let NpmRunPath$1 = {};

let Chunk = {};

function execAsync(cmd) {
  return new Promise((resolve, reject) => {
    Nodechild_process.exec(cmd, {
      encoding: "utf-8",
      env: NpmRunPath.npmRunPathEnv()
    }, (error, stdout, stderr) => {
      if (error === null) {
        if (stderr.trim().length > 0) {
          return reject(new Error(stderr.trim()));
        } else {
          return resolve(stdout.trim());
        }
      } else {
        return reject(error);
      }
    });
  });
}

let ChildProcess = {
  Chunk: Chunk,
  execAsync: execAsync
};

let Process = {};

let Path = {};

let Constants = {};

async function fileExists(path) {
  try {
    await access(path, Promises.constants.R_OK);
    return true;
  } catch (exn) {
    return false;
  }
}

let FsPromises = {
  Constants: Constants,
  fileExists: fileExists
};

export {
  NpmRunPath$1 as NpmRunPath,
  ChildProcess,
  Process,
  Path,
  FsPromises,
}
/* npm-run-path Not a pure module */
