// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Promises from "node:fs/promises";

let Chunk = {};

let ChildProcess = {
  Chunk: Chunk
};

let Process = {};

let Path = {};

let Constants = {};

async function fileExists(path) {
  try {
    await access(path, Promises.constants.R_OK);
    return true;
  } catch (exn) {
    return false;
  }
}

let FsPromises = {
  Constants: Constants,
  fileExists: fileExists
};

export {
  ChildProcess,
  Process,
  Path,
  FsPromises,
}
/* node:fs/promises Not a pure module */
