// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node from "./Node.res.mjs";
import * as Nodepath from "node:path";
import * as Stdlib_Exn from "rescript/lib/es6/Stdlib_Exn.js";
import * as Stdlib_Int from "rescript/lib/es6/Stdlib_Int.js";
import * as Picocolors from "picocolors";
import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";
import * as Nodeprocess from "node:process";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Stdlib_Promise from "rescript/lib/es6/Stdlib_Promise.js";
import * as Promises from "node:fs/promises";
import * as Nodechild_process from "node:child_process";

let rewatchAlreadyRunningRegex = /Rewatch is already running with PID (\d+)/;

let warning = "Warning number";

function rescript(optionsOpt) {
  let options = optionsOpt !== undefined ? optionsOpt : ({});
  let useRewatch = Stdlib_Option.getOr(options.useRewatch, false);
  let rescriptProcressRef = {
    contents: undefined
  };
  let logger = {
    contents: {
      info: (msg, optionsOpt) => {
        console.log(msg);
      },
      warn: (msg, optionsOpt) => {
        console.warn(msg);
      },
      error: (msg, optionsOpt) => {
        console.log(msg);
      }
    }
  };
  let command = {
    contents: "build"
  };
  let rewatchBin = {
    contents: undefined
  };
  let outputExtension = {
    contents: ".res.mjs"
  };
  let build = () => {
    let rewatchBin$1 = rewatchBin.contents;
    if (rewatchBin$1 === undefined) {
      return Nodechild_process.execSync("rescript");
    }
    if (!useRewatch) {
      return Nodechild_process.execSync("rescript");
    }
    let rewatchProcess = Nodechild_process.execSync(rewatchBin$1 + " build");
    rescriptProcressRef.contents = rewatchProcess;
    return rewatchProcess;
  };
  let watch = (logger, isRetryOpt) => {
    let isRetry = isRetryOpt !== undefined ? isRetryOpt : false;
    return new Promise((resolve, reject) => {
      let rewatchBin$1 = rewatchBin.contents;
      let processRef = rewatchBin$1 !== undefined ? (
          useRewatch ? Nodechild_process.spawn(rewatchBin$1, ["watch"]) : Nodechild_process.spawn("rescript", ["-w"])
        ) : Nodechild_process.spawn("rescript", ["-w"]);
      let buffer = {
        contents: ""
      };
      processRef.stdout.on("data", data => {
        buffer.contents = buffer.contents + data.toString();
        let lines = buffer.contents.split("\n").filter(line => !line.includes("rescript: ["));
        buffer.contents = Stdlib_Option.getOr(lines.pop(), "");
        let hasBugOrWarning = lines.some(v => {
          if (v.includes("FAILED:")) {
            return true;
          } else {
            return v.includes(warning);
          }
        });
        if (hasBugOrWarning) {
          lines.forEach(line => {
            let errorLineNumber = Stdlib_Option.getOr(Stdlib_Array.filterMap(lines, line => {
              let parts = line.split("│");
              if (parts.length !== 2) {
                return;
              }
              let number = parts[0];
              return Stdlib_Int.fromString(number, undefined);
            }).at(2), -1);
            let lineText;
            if (line.includes("We've found a bug for you!")) {
              lineText = Picocolors.red(Picocolors.bold(line));
            } else if (line.includes(errorLineNumber.toString() + " │")) {
              lineText = line.replace(/^\s+\d+/, prim => Picocolors.red(prim));
            } else if (/\.res(i?):/.test(line)) {
              let colonIndex = line.indexOf(":");
              if (colonIndex === -1) {
                lineText = line;
              } else {
                let path = line.slice(0, colonIndex);
                let range = line.slice(colonIndex + 1 | 0);
                lineText = Picocolors.cyanBright(path) + ":" + Picocolors.whiteBright(range);
              }
            } else {
              lineText = line.includes("FAILED:") ? line.replace(/FAILED:/, prim => Picocolors.redBright(prim)) : (
                  line.includes(warning) ? Picocolors.bold(Picocolors.yellowBright(line)) : line
                );
            }
            logger.error(lineText, undefined);
          });
          return;
        }
        if (lines.length === 1) {
          let line = lines[0];
          if (line.includes(">>>> Start compiling")) {
            return logger.info(Picocolors.cyanBright(line), undefined);
          }
          if (line.includes(">>>> Finish compiling")) {
            return logger.info(line.replace(/^(>>>> Finish compiling )(\d+)(.*)$/, (param, lead, number, rest) => Picocolors.cyanBright(lead) + Picocolors.yellowBright(number) + rest), undefined);
          }
          
        }
        lines.forEach(line => logger.info(line.trim(), undefined));
      });
      processRef.stderr.on("data", data => {
        let error = data.toString().trim();
        if (!(useRewatch && !isRetry)) {
          return;
        }
        let match = error.match(rewatchAlreadyRunningRegex);
        if (!(match == null) && match.length === 2) {
          let pids = match[1];
          if (pids !== undefined) {
            let pid = Stdlib_Int.fromString(pids, undefined);
            if (pid === undefined) {
              return reject(Stdlib_Exn.raiseError("Could not parse PID from rewatch error message"));
            }
            logger.error("rewatch was already running on " + pids + ", trying to kill it and restart.", undefined);
            let isKilled = Nodeprocess.process.kill(pid, "SIGKILL");
            if (!isKilled) {
              logger.error("Failed to kill rewatch process with PID " + pids, undefined);
            }
            Stdlib_Promise.$$catch(watch(logger, true).then(pref => resolve(pref)), err => {
              reject(err);
              return Promise.resolve();
            });
            return;
          }
          
        }
        logger.error(error, undefined);
        reject(Stdlib_Exn.raiseError(error));
      });
      let processName = useRewatch ? "rewatch" : "rescript";
      processRef.on("close", code => logger.info(processName + " process (" + processRef.pid.toString() + ") exited with code " + code.toString(), undefined));
      logger.info("Spawned " + processName + " (" + processRef.pid.toString() + ") in watch mode", undefined);
      resolve(processRef);
    });
  };
  return {
    name: "rescript",
    enforce: "pre",
    config: () => ({
      server: {
        watch: {
          ignored: [
            "**/lib/**",
            "**/*.res"
          ]
        }
      }
    }),
    configResolved: async resolvedConfig => {
      logger.contents = resolvedConfig.logger;
      command.contents = resolvedConfig.command;
      let rescriptConfig = Nodepath.join(Nodepath.dirname(resolvedConfig.configFile), "rescript.json");
      let match = await Node.FsPromises.fileExists(rescriptConfig);
      if (match) {
        let rescriptJson = await Promises.readFile(rescriptConfig, "utf-8");
        try {
          let match$1 = JSON.parse(rescriptJson);
          let exit = 0;
          if (typeof match$1 === "object" && match$1 !== null && !Array.isArray(match$1)) {
            let suffix = match$1.suffix;
            if (typeof suffix === "string") {
              outputExtension.contents = suffix;
            } else {
              exit = 1;
            }
          } else {
            exit = 1;
          }
          if (exit === 1) {
            logger.contents.warn("rescript.json should be an object with a 'suffix' key", undefined);
          }
          
        } catch (exn) {
          logger.contents.warn("rescript.json should be a valid JSON object", undefined);
        }
      }
      if (!useRewatch) {
        return;
      }
      try {
        let binPath = await import(Nodepath.join(Nodepath.resolve("node_modules"), "rescript/cli/bin_path.js"));
        let rewatchBinPath = Nodepath.join(binPath.absolutePath, "rewatch.exe");
        rewatchBin.contents = rewatchBinPath;
        return logger.contents.info("rewatchBin found at " + rewatchBinPath, undefined);
      } catch (e) {
        logger.contents.error("Option rewatch can only be used using the v12 alpha.", undefined);
        throw e;
      }
    },
    buildStart: async () => {
      let match = command.contents;
      if (match === "serve") {
        rescriptProcressRef.contents = await watch(logger.contents, undefined);
        return;
      } else {
        return logger.contents.info(build().toString().trim(), undefined);
      }
    },
    buildEnd: async () => Stdlib_Option.forEach(rescriptProcressRef.contents, rescriptProcressRef => {
      if (rescriptProcressRef.killed) {
        return;
      }
      let pid = rescriptProcressRef.pid;
      if (!Nodeprocess.process.kill(pid, "SIGKILL")) {
        return;
      }
      let processName = useRewatch ? "rewatch" : "rescript";
      logger.contents.info("Killed " + processName + " process with PID " + pid.toString(), undefined);
    })
  };
}

let $$default = rescript;

export {
  rescript,
  $$default as default,
}
/* Node Not a pure module */
