// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node from "./Node.res.mjs";
import * as RescriptTools_Docgen from "rescript/lib/es6/RescriptTools_Docgen.js";

function collectReactComponents(item) {
  if (item.kind !== "value") {
    return [];
  }
  if (item.name !== "make") {
    return [];
  }
  let detail = item.detail;
  if (detail === undefined) {
    return [];
  }
  switch (detail.kind) {
    case "record" :
    case "variant" :
      return [];
    case "signature" :
      if (detail.details.returnType.path === "React.element") {
        return [item.id];
      } else {
        return [];
      }
  }
}

async function transform(code, resPath) {
  let docOutput = await Node.ChildProcess.execAsync("rescript-tools doc " + resPath);
  let json = JSON.parse(docOutput);
  let doc = RescriptTools_Docgen.decodeFromJson(json);
  let hasReactComponent = new Set(doc.items.flatMap(collectReactComponents));
  console.log(hasReactComponent, doc);
  return code;
}

await transform("", "/Users/nojaf/Projects/vite-plugin-rescript/tests/Initial.res");

export {
  collectReactComponents,
  transform,
}
/*  Not a pure module */
