// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node from "./Node.res.mjs";
import * as OxcParser from "oxc-parser";
import * as Promises from "node:fs/promises";
import * as RescriptTools_Docgen from "rescript/lib/es6/RescriptTools_Docgen.js";

function collectReactComponents(item) {
  if (item.kind !== "value") {
    return [];
  }
  if (item.name !== "make") {
    return [];
  }
  let detail = item.detail;
  if (detail === undefined) {
    return [];
  }
  switch (detail.kind) {
    case "record" :
    case "variant" :
      return [];
    case "signature" :
      if (detail.details.returnType.path === "React.element") {
        return [item.id];
      } else {
        return [];
      }
  }
}

async function transform(code, resPath) {
  let docOutput = await Node.ChildProcess.execAsync("rescript-tools doc " + resPath);
  let json = JSON.parse(docOutput);
  let doc = RescriptTools_Docgen.decodeFromJson(json);
  let reactComponents = new Set(doc.items.flatMap(collectReactComponents));
  if (reactComponents.size === 0) {
    return code;
  }
  let match = await OxcParser.parseAsync(resPath + ".mjs", code);
  match.program.body.forEach(statement => {
    let match = statement.type;
    if (typeof match !== "string") {
      return;
    }
    if (match !== "ExportNamedDeclaration") {
      return;
    }
    let specifiers = statement.specifiers;
    if (!Array.isArray(specifiers)) {
      return;
    }
    let exportSpecifiers = specifiers.flatMap(specifier => {
      if (typeof specifier !== "object" || Array.isArray(specifier)) {
        return [];
      }
      let match = specifier.type;
      if (typeof match === "string") {
        if (match === "ExportSpecifier") {
          return [specifier];
        } else {
          return [];
        }
      } else {
        return [];
      }
    });
    console.log(exportSpecifiers);
  });
  return match.magicString.toString();
}

let code = await Promises.readFile("/Users/nojaf/Projects/vite-plugin-rescript/tests/Initial.res.mjs", "utf-8");

await transform(code, "/Users/nojaf/Projects/vite-plugin-rescript/tests/Initial.res");

export {
  collectReactComponents,
  transform,
  code,
}
/* code Not a pure module */
