name: Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - name: Install node_modules
        run: bun install --frozen-lockfile

      - name: Check version
        run: bun run ./scripts/check-version.ts

      - name: Bundle
        run: bun run bundle
